export const data = [
  {
    id: 1,
    image: "image_url_1",
    nameEnglish: "Black Urad Dal",
    nameTelugu: "పొట్టు మినపప్పు (Pottu Minapappu)",
    quantity: "50gm",
  },
  {
    id: 2,
    image: "image_url_2",
    nameEnglish: "Urad Dal",
    nameTelugu: "మినపగుళ్ళు (Minapagullu)",
    quantity: "50gm",
  },
  {
    id: 3,
    image: "image_url_3",
    nameEnglish: "Urad Dal Split",
    nameTelugu: "సాయి మినపప్పు (Sai Minapappu)",
    quantity: "50gm",
  },
  {
    id: 4,
    image: "image_url_4",
    nameEnglish: "Toor Dal",
    nameTelugu: "కందిపప్పు (Kandhipappu)",
    quantity: "50gm",
  },
  {
    id: 5,
    image: "image_url_5",
    nameEnglish: "Red Gram",
    nameTelugu: "ఎర్ర కందిపప్పు (Erra Kandhipappu)",
    quantity: "50gm",
  },
  {
    id: 6,
    image: "image_url_6",
    nameEnglish: "Green Moong Dal",
    nameTelugu: "పచ్చ పెసలు (Pacha Pesalu)",
    quantity: "50gm",
  },
  {
    id: 7,
    image: "image_url_7",
    nameEnglish: "Black Moong Dal",
    nameTelugu: "నల్ల పెసలు (Nalla Pesalu)",
    quantity: "50gm",
  },
  {
    id: 8,
    image: "image_url_8",
    nameEnglish: "Moong Dal Split",
    nameTelugu: "సాయి పెసర పప్పు (Sai Pesara Pappu)",
    quantity: "50gm",
  },
  {
    id: 9,
    image: "image_url_9",
    nameEnglish: "Bengal Gram",
    nameTelugu: "శనగలు (Senagalu)",
    quantity: "50gm",
  },
  {
    id: 10,
    image: "image_url_10",
    nameEnglish: "Bengal Gram Split",
    nameTelugu: "పచ్చి సెనగపప్పు (Pachi Sengapappu)",
    quantity: "50gm",
  },
  {
    id: 11,
    image: "image_url_11",
    nameEnglish: "Chick Peas",
    nameTelugu: "కాబూలీ సెనగలు (Kabuli Senagalu)",
    quantity: "50gm",
  },
  {
    id: 12,
    image: "image_url_12",
    nameEnglish: "Tamarind",
    nameTelugu: "చింతపండు (Chintapandu)",
    quantity: "50gm",
  },
  {
    id: 13,
    image: "image_url_13",
    nameEnglish: "Red Chilli Powder",
    nameTelugu: "కారం (Karam)",
    quantity: "50gm",
  },
  {
    id: 14,
    image: "image_url_14",
    nameEnglish: "Turmeric",
    nameTelugu: "పసుపు (Pasupu)",
    quantity: "50gm",
  },
  {
    id: 15,
    image: "image_url_15",
    nameEnglish: "Rock Salt",
    nameTelugu: "కల్లు ఉప్పు (Kallu Uppu)",
    quantity: "50gm",
  },
  {
    id: 16,
    image: "image_url_16",
    nameEnglish: "Salt",
    nameTelugu: "ఉప్పు (Uppu)",
    quantity: "50gm",
  },
  {
    id: 17,
    image: "image_url_17",
    nameEnglish: "Idly Rava",
    nameTelugu: "ఇడ్లి రవ్వ (Idli Ravva)",
    quantity: "50gm",
  },
  {
    id: 18,
    image: "image_url_18",
    nameEnglish: "Sooji",
    nameTelugu: "బొంబాయి రవ్వ (Bombay Ravva)",
    quantity: "50gm",
  },
  {
    id: 19,
    image: "image_url_19",
    nameEnglish: "Wheat Rava",
    nameTelugu: "గోధుమ రవ్వ (Godhuma Ravva)",
    quantity: "50gm",
  },
  {
    id: 20,
    image: "image_url_20",
    nameEnglish: "Gram Flour",
    nameTelugu: "శనగ పిండి (Shanaga Pindi)",
    quantity: "50gm",
  },
  {
    id: 21,
    image: "image_url_21",
    nameEnglish: "Wheat Flour",
    nameTelugu: "గోధుమ పిండి (Godhuma Pindi)",
    quantity: "50gm",
  },
  {
    id: 22,
    image: "image_url_22",
    nameEnglish: "Maida",
    nameTelugu: "మైదా (Maida)",
    quantity: "50gm",
  },
  {
    id: 23,
    image: "image_url_23",
    nameEnglish: "Corn Flour",
    nameTelugu: "కర్న్ ఫ్లోర్ (Corn Flour)",
    quantity: "50gm",
  },
  {
    id: 24,
    image: "image_url_24",
    nameEnglish: "Rice Flour",
    nameTelugu: "బియ్యం పిండి (Biyyam Pindi)",
    quantity: "50gm",
  },
  {
    id: 25,
    image: "image_url_25",
    nameEnglish: "Coriander",
    nameTelugu: "కొత్తిమీర (Kothimeera)",
    quantity: "50gm",
  },
  {
    id: 26,
    image: "image_url_26",
    nameEnglish: "Cumin Seeds",
    nameTelugu: "జీలకర్ర (Jeelakarra)",
    quantity: "50gm",
  },
  {
    id: 27,
    image: "image_url_27",
    nameEnglish: "Mustard",
    nameTelugu: "ఆవాలు (Avalu)",
    quantity: "50gm",
  },
  {
    id: 28,
    image: "image_url_28",
    nameEnglish: "Pepper",
    nameTelugu: "మిరపకాయ (Mirapakaya)",
    quantity: "50gm",
  },
  {
    id: 29,
    image: "image_url_29",
    nameEnglish: "Cardamom",
    nameTelugu: "ఏలకులు (Elakulu)",
    quantity: "50gm",
  },
  {
    id: 30,
    image: "image_url_30",
    nameEnglish: "Black Cardamom",
    nameTelugu: "నల్ల ఏలకులు (Nalla Elakulu)",
    quantity: "50gm",
  },
  {
    id: 31,
    image: "image_url_31",
    nameEnglish: "Tailed Pepper",
    nameTelugu: "కాటి మిరపకాయ (Kati Mirapakaya)",
    quantity: "50gm",
  },
  {
    id: 32,
    image: "image_url_32",
    nameEnglish: "Poppy Seeds",
    nameTelugu: "గసగసాలు (Gasagasaalu)",
    quantity: "50gm",
  },
  {
    id: 33,
    image: "image_url_33",
    nameEnglish: "Dry Coconut",
    nameTelugu: "ఆడ కొబ్బరి (Aada Kobbari)",
    quantity: "50gm",
  },
  {
    id: 34,
    image: "image_url_34",
    nameEnglish: "Fenugreek",
    nameTelugu: "మెంతులు (Menthulu)",
    quantity: "50gm",
  },
  {
    id: 35,
    image: "image_url_35",
    nameEnglish: "Coriander Powder",
    nameTelugu: "ధనియాల పొడి (Dhaniyala podi)",
    quantity: "50gm",
  },
  {
    id: 36,
    image: "image_url_36",
    nameEnglish: "Cumin Powder",
    nameTelugu: "జీలకర్ర పొడి (Jeelakarra Podi)",
    quantity: "50gm",
  },
  {
    id: 37,
    image: "image_url_37",
    nameEnglish: "Garam Masala",
    nameTelugu: "గరం మసాలా (Garam Masala)",
    quantity: "50gm",
  },
  {
    id: 38,
    image: "image_url_38",
    nameEnglish: "Bay Leaf",
    nameTelugu: "బిరియాని ఆకు (Biriyani Aaku)",
    quantity: "50gm",
  },
  {
    id: 39,
    image: "image_url_39",
    nameEnglish: "Stick Cinnamon",
    nameTelugu: "దాల్చిన (Dalchini)",
    quantity: "50gm",
  },
  {
    id: 40,
    image: "image_url_40",
    nameEnglish: "Cloves",
    nameTelugu: "లవంగాలు (Lavangalu)",
    quantity: "50gm",
  },
  {
    id: 41,
    image: "image_url_41",
    nameEnglish: "Kapok Buds",
    nameTelugu: "పుగుతా (Pugutha)",
    quantity: "50gm",
  },
  {
    id: 42,
    image: "image_url_42",
    nameEnglish: "Star Anise",
    nameTelugu: "అనాసు పువ్వు (Anasu Puvvu)",
    quantity: "50gm",
  },
  {
    id: 43,
    image: "image_url_43",
    nameEnglish: "Mace",
    nameTelugu: "జాతి పత్రి (Jathi Patra)",
    quantity: "50gm",
  },
  {
    id: 44,
    image: "image_url_44",
    nameEnglish: "Nutmeg",
    nameTelugu: "జాజికాయ (Jajikaya)",
    quantity: "50gm",
  },
  {
    id: 45,
    image: "image_url_45",
    nameEnglish: "Asafoetida",
    nameTelugu: "ఇంగువ (Inguva)",
    quantity: "50gm",
  },
  {
    id: 46,
    image: "image_url_46",
    nameEnglish: "Sago",
    nameTelugu: "సగ్గు బియ్యం (Saggu Biyam)",
    quantity: "50gm",
  },
  {
    id: 47,
    image: "image_url_47",
    nameEnglish: "Vermicelli",
    nameTelugu: "సేమియా (Semiya)",
    quantity: "50gm",
  },
  {
    id: 48,
    image: "image_url_48",
    nameEnglish: "Ginger",
    nameTelugu: "అల్లం (Allam)",
    quantity: "50gm",
  },
  {
    id: 49,
    image: "image_url_49",
    nameEnglish: "Dry Ginger",
    nameTelugu: "శోంతి (Shonti)",
    quantity: "50gm",
  },
  {
    id: 50,
    image: "image_url_50",
    nameEnglish: "Shahijira",
    nameTelugu: "శాహజీర (Shahajira)",
    quantity: "50gm",
  },
  {
    id: 51,
    image: "image_url_51",
    nameEnglish: "Sesame Seeds",
    nameTelugu: "నువ్వులు (Nuvvulu)",
    quantity: "50gm",
  },
  {
    id: 52,
    image: "image_url_52",
    nameEnglish: "Black Sesame Seeds",
    nameTelugu: "నల్ల నువ్వులు (Nalla Nuvvulu)",
    quantity: "50gm",
  },
  {
    id: 53,
    image: "image_url_53",
    nameEnglish: "Roasted Bengalgram",
    nameTelugu: "పుట్నల సెనగలు (Putnala Senagalu)",
    quantity: "50gm",
  },
  {
    id: 54,
    image: "image_url_54",
    nameEnglish: "Groundnuts",
    nameTelugu: "పల్లి (Palli)",
    quantity: "50gm",
  },
  {
    id: 55,
    image: "image_url_55",
    nameEnglish: "Fennel Seeds",
    nameTelugu: "సోంపు (Sompu)",
    quantity: "50gm",
  },
  {
    id: 56,
    image: "image_url_56",
    nameEnglish: "Soya Chunks",
    nameTelugu: "సోయా వడియాలు (Soya Vadiyalu)",
    quantity: "50gm",
  },
  {
    id: 57,
    image: "image_url_57",
    nameEnglish: "Sunflower Oil",
    nameTelugu: "సన్‌ఫ్లవర్ ఆయిల్ (Sunflower Oil)",
    quantity: "50gm",
  },
  {
    id: 58,
    image: "image_url_58",
    nameEnglish: "Coconut Oil",
    nameTelugu: "కొబ్బరి నూనె (Kobbari Nune)",
    quantity: "50gm",
  },
  {
    id: 59,
    image: "image_url_59",
    nameEnglish: "Sesame Oil",
    nameTelugu: "నువ్వుల నూనె (Nuvvula Nune)",
    quantity: "50gm",
  },
  {
    id: 60,
    image: "image_url_60",
    nameEnglish: "Onions",
    nameTelugu: "ఉల్లిపాయలు (Ullipayalu)",
    quantity: "50gm",
  },
  {
    id: 61,
    image: "image_url_61",
    nameEnglish: "Garlic",
    nameTelugu: "వెల్లుల్లి (Vellulli)",
    quantity: "50gm",
  },
  {
    id: 62,
    image: "image_url_62",
    nameEnglish: "Dry Red Chilli",
    nameTelugu: "ఎర్ర మిరపకాయ (Erra Mirapakaya)",
    quantity: "50gm",
  },
  {
    id: 63,
    image: "image_url_63",
    nameEnglish: "Jaggery",
    nameTelugu: "బెల్లం (Bellam)",
    quantity: "50gm",
  },
  {
    id: 64,
    image: "image_url_64",
    nameEnglish: "Sugar",
    nameTelugu: "పంచదార (Panchadara)",
    quantity: "50gm",
  },
  {
    id: 65,
    image: "image_url_65",
    nameEnglish: "Coconut",
    nameTelugu: "కొబ్బరి (Kobbari)",
    quantity: "50gm",
  },
  {
    id: 66,
    image: "image_url_66",
    nameEnglish: "Red Cow Peas",
    nameTelugu: "అలసందలు (Alasandalu)",
    quantity: "50gm",
  },
  {
    id: 67,
    image: "image_url_67",
    nameEnglish: "Carrom Seeds",
    nameTelugu: "వాము (Vamu)",
    quantity: "50gm",
  },
  {
    id: 68,
    image: "image_url_68",
    nameEnglish: "Cashew Nuts",
    nameTelugu: "జీడిపప్పు (Jeedi Pappu)",
    quantity: "50gm",
  },
  {
    id: 69,
    image: "image_url_69",
    nameEnglish: "Almonds",
    nameTelugu: "బాదం (Badam)",
    quantity: "50gm",
  },
  {
    id: 70,
    image: "image_url_70",
    nameEnglish: "Raisins",
    nameTelugu: "కిష్మిష్ (Kishmish)",
    quantity: "50gm",
  },
];
