export const data = [
  {
    id: 1,
    image: "image_url_1",
    nameEnglish: "Black Urad Dal",
    nameTelugu: "పొట్టు మినపప్పు (Pottu Minapappu)",
    quantity: "50gm",
  },
  {
    id: 2,
    image: "image_url_2",
    nameEnglish: "Urad Dal",
    nameTelugu: "మినపగుళ్ళు (Minapagullu)",
    quantity: "50gm",
  },
  {
    id: 3,
    image: "image_url_3",
    nameEnglish: "Urad Dal Split",
    nameTelugu: "సాయి మినపప్పు (Sai Minapappu)",
    quantity: "50gm",
  },
  {
    id: 4,
    image: "image_url_4",
    nameEnglish: "Toor Dal",
    nameTelugu: "కందిపప్పు (Kandhipappu)",
    quantity: "50gm",
  },
  {
    id: 5,
    image: "image_url_5",
    nameEnglish: "Red Gram",
    nameTelugu: "ఎర్ర కందిపప్పు (Erra Kandhipappu)",
    quantity: "50gm",
  },
  {
    id: 6,
    image: "image_url_6",
    nameEnglish: "Green Moong Dal",
    nameTelugu: "పచ్చ పెసలు (Pacha Pesalu)",
    quantity: "50gm",
  },
  {
    id: 7,
    image: "image_url_7",
    nameEnglish: "Black Moong Dal",
    nameTelugu: "నల్ల పెసలు (Nalla Pesalu)",
    quantity: "50gm",
  },
  {
    id: 8,
    image: "image_url_8",
    nameEnglish: "Moong Dal Split",
    nameTelugu: "సాయి పెసర పప్పు (Sai Pesara Pappu)",
    quantity: "50gm",
  },
  {
    id: 9,
    image: "image_url_9",
    nameEnglish: "Bengal Gram",
    nameTelugu: "శనగలు (Senagalu)",
    quantity: "50gm",
  },
  {
    id: 10,
    image: "image_url_10",
    nameEnglish: "Bengal Gram Split",
    nameTelugu: "పచ్చి సెనగపప్పు (Pachi Sengapappu)",
    quantity: "50gm",
  },
  {
    id: 11,
    image: "image_url_11",
    nameEnglish: "Chick Peas",
    nameTelugu: "కాబూలీ సెనగలు (Kabuli Senagalu)",
    quantity: "50gm",
  },
  {
    id: 12,
    image: "image_url_12",
    nameEnglish: "Tamarind",
    nameTelugu: "చింతపండు (Chintapandu)",
    quantity: "50gm",
  },
  {
    id: 13,
    image: "image_url_13",
    nameEnglish: "Red Chilli Powder",
    nameTelugu: "కారం (Karam)",
    quantity: "50gm",
  },
  {
    id: 14,
    image: "image_url_14",
    nameEnglish: "Turmeric",
    nameTelugu: "పసుపు (Pasupu)",
    quantity: "50gm",
  },
];
